#Proyecto de Aprendizaje Automático.
#Predicción del consumo mensual de gas envasado en Tierra del Fuego.

## Introducción

El presente proyecto tiene como objetivo desarrollar un modelo de Aprendizaje Automático orientado a la predicción del consumo mensual de gas envasado en Tierra del Fuego.

Para ello se utilizarán datasets oficiales relacionados con consumo energético, cantidad de usuarios empadronados y variables climáticas correspondientes a la provincia.

El dataset energético contiene registros mensuales históricos de consumo de gas envasado y cantidad de usuarios, mientras que el dataset climático incluye variables meteorológicas como temperatura, precipitaciones y días con nieve correspondientes a Río Grande y Ushuaia.

A partir de ambas fuentes se construirá un dataset integrado orientado al entrenamiento de modelos supervisados de regresión.

In [306]:
# Importamos librerías necesarias
import pandas as pd
import numpy as np

In [307]:
# Cargamos dataset de gas envasado
gas = pd.read_excel(
    "/15_3_07-Usuario-y-consumo-de-gas-envasado.xlsx",
    sheet_name="Gas kilos",
    skiprows=5
)

# Mostramos primeras filas
gas.head()

,ENERO,619090,704205,977249,1171046,1224619,1409402,1417098,1586791,1634010,1490557,1460855,1321110
0,FEBRERO,645720.0,744285.0,982578.0,1112145.0,1258621.0,1493190.0,1423402.0,1546208.0,1609924.0,1501791.0,1486220.0,1333061
1,MARZO,696210.0,813460.0,1107447.0,1310560.0,1452585.0,1521365.0,1542645.0,1600790.0,1697638.0,1588816.0,1507445.0,1342738
2,ABRIL,717420.0,917345.0,1293634.0,1425735.0,1560989.0,1963606.0,2240437.0,1713818.0,1784775.0,1686891.0,1532726.0,1362904
3,MAYO,1377010.0,1638965.0,2109628.0,2282768.0,2656253.0,2716358.0,2756552.0,3001549.0,3024410.0,2942394.0,2840416.0,2550121
4,JUNIO,1448205.0,1850500.0,2033353.0,2495662.0,2667335.0,2775537.0,2929347.0,3066442.0,3047450.0,3029466.0,2895266.0,2522754

In [308]:
# Mostramos información general del dataset
gas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ENERO    14 non-null     object
 1   619090   12 non-null     float64
 2   704205   12 non-null     float64
 3   977249   12 non-null     float64
 4   1171046  12 non-null     float64
 5   1224619  12 non-null     float64
 6   1409402  12 non-null     float64
 7   1417098  12 non-null     float64
 8   1586791  12 non-null     float64
 9   1634010  12 non-null     float64
 10  1490557  12 non-null     float64
 11  1460855  12 non-null     float64
 12  1321110  12 non-null     object
dtypes: float64(11), object(2)
memory usage: 1.7+ KB

In [309]:
# Mostramos nombres de columnas
gas.columns

Index(['ENERO',  619090,  704205,  977249, 1171046, 1224619, 1409402, 1417098,
       1586791, 1634010, 1490557, 1460855, 1321110],
      dtype='object')

In [310]:
# Cargamos nuevamente el dataset de gas envasado sin tomar encabezados automáticos
gas_raw = pd.read_excel(
    "/15_3_07-Usuario-y-consumo-de-gas-envasado.xlsx",
    sheet_name="Gas kilos",
    header=None
)

# Mostramos las primeras filas para ubicar manualmente la tabla
gas_raw.head(20)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,"Gas envasado consumido en kilogramos, por mes....",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MES / AÑO,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025
4,NaN,Kilos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ENERO,619090,704205.0,977249.0,1171046.0,1224619.0,1409402.0,1417098.0,1586791.0,1634010.0,1490557.0,1460855.0,1321110
6,FEBRERO,645720,744285.0,982578.0,1112145.0,1258621.0,1493190.0,1423402.0,1546208.0,1609924.0,1501791.0,1486220.0,1333061
7,MARZO,696210,813460.0,1107447.0,1310560.0,1452585.0,1521365.0,1542645.0,1600790.0,1697638.0,1588816.0,1507445.0,1342738
8,ABRIL,717420,917345.0,1293634.0,1425735.0,1560989.0,1963606.0,2240437.0,1713818.0,1784775.0,1686891.0,1532726.0,1362904
9,MAYO,1377010,1638965.0,2109628.0,2282768.0,2656253.0,2716358.0,2756552.0,3001549.0,3024410.0,2942394.0,2840416.0,2550121
10,JUNIO,1448205,1850500.0,2033353.0,2495662.0,2667335.0,2775537.0,2929347.0,3066442.0,3047450.0,3029466.0,2895266.0,2522754
11,JULIO,1476035,2038280.0,2042124.0,2379978.0,2739864.0,2752811.0,3187302.0,3045814.0,3111061.0,2971108.0,2840208.0,2521557
12,AGOSTO,1483360,1811740.0,2098946.0,2392515.0,2629250.0,2784412.0,3067224.0,3089907.0,3009032.0,2725206.0,2872820.0,2481718
13,SEPTIEMBRE,1469655,1696750.0,2041366.0,2423921.0,2618978.0,2710662.0,2939101.0,3000540.0,3006070.0,2833227.0,2849464.0,2199441
14,OCTUBRE,827295,1058747.0,1271338.0,1472306.0,1553597.0,1979461.0,1701524.0,1739631.0,1640599.0,1489428.0,1476842.0,1273663
15,NOVIEMBRE,864300,1107095.0,1217038.0,1496132.0,1587613.0,1605707.0,1660155.0,1685282.0,1589200.0,1505818.0,1452301.0,…
16,DICIEMBRE,806455,1066347.0,1239448.0,1453739.0,1481840.0,1500160.0,1639564.0,1661362.0,1507057.0,1510564.0,1321782.0,…
17,TOTAL ANUAL,12430755,15447719.0,18414149.0,21416507.0,23431544.0,25212671.0,26504351.0,26738134.0,26661226.0,25275266.0,24536345.0,1321110
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,... Dato no disponible a la fecha de presentac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [311]:
# Seleccionamos solamente la tabla útil
gas_limpio = gas_raw.iloc[5:17, 0:13]

# Renombramos columnas
gas_limpio.columns = [
    "mes",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025"
]

# Mostramos resultado
gas_limpio.head()

,mes,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
5,ENERO,619090,704205.0,977249.0,1171046.0,1224619.0,1409402.0,1417098.0,1586791.0,1634010.0,1490557.0,1460855.0,1321110
6,FEBRERO,645720,744285.0,982578.0,1112145.0,1258621.0,1493190.0,1423402.0,1546208.0,1609924.0,1501791.0,1486220.0,1333061
7,MARZO,696210,813460.0,1107447.0,1310560.0,1452585.0,1521365.0,1542645.0,1600790.0,1697638.0,1588816.0,1507445.0,1342738
8,ABRIL,717420,917345.0,1293634.0,1425735.0,1560989.0,1963606.0,2240437.0,1713818.0,1784775.0,1686891.0,1532726.0,1362904
9,MAYO,1377010,1638965.0,2109628.0,2282768.0,2656253.0,2716358.0,2756552.0,3001549.0,3024410.0,2942394.0,2840416.0,2550121

In [312]:
# Transformamos el dataset de formato matriz a formato tabular
gas_ml = gas_limpio.melt(
    id_vars="mes",
    var_name="anio",
    value_name="consumo_gas_kg"
)

# Mostramos primeras filas
gas_ml.head()

       mes  anio consumo_gas_kg
0    ENERO  2014         619090
1  FEBRERO  2014         645720
2    MARZO  2014         696210
3    ABRIL  2014         717420
4     MAYO  2014        1377010

In [313]:
# Mostramos información general del dataset transformado
gas_ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mes             144 non-null    object
 1   anio            144 non-null    object
 2   consumo_gas_kg  144 non-null    object
dtypes: object(3)
memory usage: 3.5+ KB

In [314]:
# Cargamos dataset de usuarios empadronados
usuarios_raw = pd.read_excel(
    "/15_3_07-Usuario-y-consumo-de-gas-envasado.xlsx",
    sheet_name="Usuario",
    header=None
)

# Mostramos primeras filas
usuarios_raw.head(20)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Cantidad de usuarios empadronados de gas envas...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Meses/Años,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025
3,Enero,4868.000000,5534.000000,6278.000000,6808.000000,7754.000000,7968.000000,8058.000000,7883.000000,7925.000000,7112.000000,6681.000000,5920
4,Febrero,4966.000000,5535.000000,6346.000000,6895.000000,7828.000000,7977.000000,7980.000000,7982.000000,7967.000000,7188.000000,6749.000000,5989
5,Marzo,4982.000000,5525.000000,6403.000000,6989.000000,7909.000000,8017.000000,7614.000000,8073.000000,8011.000000,7229.000000,6752.000000,6036
6,Abril,4888.000000,5573.000000,6496.000000,7056.000000,7316.000000,8055.000000,7865.000000,8094.000000,7885.000000,7371.000000,6956.000000,6021
7,Mayo,5106.000000,5780.000000,6576.000000,7167.000000,7450.000000,8121.000000,7925.000000,8184.000000,7782.000000,7322.000000,6821.000000,6027
8,Junio,5291.000000,5961.000000,6662.000000,7230.000000,7585.000000,8489.000000,7981.000000,8278.000000,7767.000000,7304.000000,6832.000000,6009
9,Julio,5249.000000,6031.000000,6768.000000,7357.000000,7726.000000,8222.000000,8027.000000,8202.000000,7649.000000,7118.000000,6832.000000,6001
10,Agosto,5337.000000,6056.000000,6840.000000,7466.000000,7783.000000,8218.000000,8031.000000,8248.000000,7514.000000,6528.000000,6875.000000,6006
11,Septiembre,5318.000000,6103.000000,6896.000000,7528.000000,7844.000000,8203.000000,8081.000000,8187.000000,7587.000000,6777.000000,6794.000000,5975
12,Octubre,5459.000000,6171.000000,6967.000000,7588.000000,7884.000000,8091.000000,7916.000000,7918.000000,7350.000000,6848.000000,6547.000000,5977
13,Noviembre,5485.000000,6222.000000,7002.000000,7652.000000,7916.000000,8083.000000,7967.000000,7859.000000,6821.000000,6795.000000,6328.000000,…
14,Diciembre,5477.000000,6214.000000,6678.000000,7715.000000,7962.000000,8070.000000,7846.000000,7904.000000,7031.000000,6742.000000,5779.000000,…
15,Total anual,62426.000000,70705.000000,79912.000000,87451.000000,92957.000000,97514.000000,95291.000000,96812.000000,91289.000000,84334.000000,79946.000000,23966
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Promedio Anual,5202.166667,5892.083333,6659.333333,7287.583333,7746.416667,8126.166667,7940.916667,8067.666667,7607.416667,7027.833333,6662.166667,1997.166667
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,... Dato no disponible a la fecha de presentac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [315]:
# Seleccionamos únicamente las filas útiles
usuarios_limpio = usuarios_raw.iloc[3:15].copy()

# Renombramos columnas
usuarios_limpio.columns = [
    "mes",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025"
]

# Mostramos resultado
usuarios_limpio.head()

,mes,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
3,Enero,4868.0,5534.0,6278.0,6808.0,7754.0,7968.0,8058.0,7883.0,7925.0,7112.0,6681.0,5920
4,Febrero,4966.0,5535.0,6346.0,6895.0,7828.0,7977.0,7980.0,7982.0,7967.0,7188.0,6749.0,5989
5,Marzo,4982.0,5525.0,6403.0,6989.0,7909.0,8017.0,7614.0,8073.0,8011.0,7229.0,6752.0,6036
6,Abril,4888.0,5573.0,6496.0,7056.0,7316.0,8055.0,7865.0,8094.0,7885.0,7371.0,6956.0,6021
7,Mayo,5106.0,5780.0,6576.0,7167.0,7450.0,8121.0,7925.0,8184.0,7782.0,7322.0,6821.0,6027

In [316]:
# Transformamos dataset de usuarios a formato tabular
usuarios_ml = usuarios_limpio.melt(
    id_vars="mes",
    var_name="anio",
    value_name="cantidad_usuarios"
)

# Mostramos primeras filas
usuarios_ml.head()

       mes  anio cantidad_usuarios
0    Enero  2014            4868.0
1  Febrero  2014            4966.0
2    Marzo  2014            4982.0
3    Abril  2014            4888.0
4     Mayo  2014            5106.0

In [317]:
# Unimos dataset de gas y usuarios
dataset = pd.merge(
    gas_ml,
    usuarios_ml,
    on=["mes", "anio"],
    how="inner"
)

# Mostramos primeras filas
dataset.head()

Empty DataFrame
Columns: [mes, anio, consumo_gas_kg, cantidad_usuarios]
Index: []

In [318]:
# Normalizamos los nombres de los meses para que coincidan en ambos datasets
gas_ml["mes"] = gas_ml["mes"].str.upper()
usuarios_ml["mes"] = usuarios_ml["mes"].str.upper()

# Convertimos el año a texto en ambos datasets
gas_ml["anio"] = gas_ml["anio"].astype(str)
usuarios_ml["anio"] = usuarios_ml["anio"].astype(str)

# Volvemos a unir dataset de gas y usuarios
dataset = pd.merge(
    gas_ml,
    usuarios_ml,
    on=["mes", "anio"],
    how="inner"
)

# Mostramos las primeras filas
dataset.head(10)

          mes  anio consumo_gas_kg cantidad_usuarios
0       ENERO  2014         619090            4868.0
1     FEBRERO  2014         645720            4966.0
2       MARZO  2014         696210            4982.0
3       ABRIL  2014         717420            4888.0
4        MAYO  2014        1377010            5106.0
5       JUNIO  2014        1448205            5291.0
6       JULIO  2014        1476035            5249.0
7      AGOSTO  2014        1483360            5337.0
8  SEPTIEMBRE  2014        1469655            5318.0
9     OCTUBRE  2014         827295            5459.0

In [319]:
# Mostramos dimensiones del dataset
dataset.shape

(144, 4)

In [320]:
# Cargamos dataset climático
clima_raw = pd.read_excel(
    "/22_2_01_Meteorologia_Temperatura_Precipitaciones.xlsx"
)

# Mostramos primeras filas
clima_raw.head()

  Meteorología. Temperatura máxima media, mínima media y media. Precipitaciones y días con nieve. Río Grande y Ushuaia, provincia de Tierra del Fuego AeIAS.
0                                                NaN
1                                      Datos anuales
2                                    Datos mensuales
3                                      Ficha Técnica
4                                                NaN

In [321]:
# Leemos nuevamente el dataset climático salteando filas innecesarias
clima_raw = pd.read_excel(
    "/22_2_01_Meteorologia_Temperatura_Precipitaciones.xlsx",
    sheet_name="por mes",
    skiprows=5
)

# Mostramos primeras filas
clima_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,°C,NaN,NaN,NaN,NaN,mm,días,NaN,°C,NaN,NaN,NaN,mm,días
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,Enero,16.5,6.2,11.3,NaN,NaN,13.7,0,NaN,10.8,9.4,10.1,NaN,30.8,0
3,NaN,Febrero,16,5.1,10.3,NaN,NaN,38.4,0,NaN,9.5,8.3,8.9,NaN,29,0
4,NaN,Marzo,13.9,4.32,8.9,NaN,NaN,20.7,0,NaN,9.1,7.9,8.5,NaN,64.6,1

In [322]:
# Mostramos nombres reales de columnas del dataset climático
clima_raw.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15'],
      dtype='object')

In [323]:
# Seleccionamos únicamente columnas útiles
clima_limpio = clima_raw.iloc[2:].copy()

# Seleccionamos columnas importantes
clima_limpio = clima_limpio[
    [
        "Unnamed: 0",
        "Unnamed: 1",
        "Unnamed: 2",
        "Unnamed: 3",
        "Unnamed: 4",
        "Unnamed: 7",
        "Unnamed: 8",
        "Unnamed: 10",
        "Unnamed: 11",
        "Unnamed: 12",
        "Unnamed: 14",
        "Unnamed: 15"
    ]
]

# Renombramos columnas
clima_limpio.columns = [
    "anio",
    "mes",
    "temp_max_rg",
    "temp_min_rg",
    "temp_media_rg",
    "precipitacion_rg",
    "nieve_rg",
    "temp_max_ush",
    "temp_min_ush",
    "temp_media_ush",
    "precipitacion_ush",
    "nieve_ush"
]

# Mostramos primeras filas
clima_limpio.head()

,anio,mes,temp_max_rg,temp_min_rg,temp_media_rg,precipitacion_rg,nieve_rg,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
2,2009,Enero,16.5,6.2,11.3,13.7,0,10.8,9.4,10.1,30.8,0
3,NaN,Febrero,16,5.1,10.3,38.4,0,9.5,8.3,8.9,29,0
4,NaN,Marzo,13.9,4.32,8.9,20.7,0,9.1,7.9,8.5,64.6,1
5,NaN,Abril,9.4,2.5,5.8,59.8,0,6.1,5.2,5.7,86.2,1
6,NaN,Mayo,6.3,-1.2,2.1,11.4,1,s/d,s/d,2.6,59.2,4

In [324]:
# Eliminamos filas vacías
clima_limpio = clima_limpio.dropna(subset=["mes"])

# Reiniciamos índices
clima_limpio = clima_limpio.reset_index(drop=True)

# Mostramos información general
clima_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   anio               17 non-null     object
 1   mes                204 non-null    object
 2   temp_max_rg        204 non-null    object
 3   temp_min_rg        204 non-null    object
 4   temp_media_rg      204 non-null    float64
 5   precipitacion_rg   204 non-null    object
 6   nieve_rg           204 non-null    object
 7   temp_max_ush       204 non-null    object
 8   temp_min_ush       204 non-null    object
 9   temp_media_ush     204 non-null    object
 10  precipitacion_ush  204 non-null    object
 11  nieve_ush          204 non-null    object
dtypes: float64(1), object(11)
memory usage: 19.3+ KB

In [325]:
# Completamos hacia abajo los años faltantes
# En el Excel el año aparece solo en enero de cada bloque anual
clima_limpio["anio"] = clima_limpio["anio"].ffill()

# Verificamos primeras filas
clima_limpio.head(15)

/tmp/ipykernel_1571/3634031272.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clima_limpio["anio"] = clima_limpio["anio"].ffill()

,anio,mes,temp_max_rg,temp_min_rg,temp_media_rg,precipitacion_rg,nieve_rg,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
0,2009,Enero,16.5,6.2,11.3,13.7,0,10.8,9.4,10.1,30.8,0
1,2009,Febrero,16,5.1,10.3,38.4,0,9.5,8.3,8.9,29,0
2,2009,Marzo,13.9,4.32,8.9,20.7,0,9.1,7.9,8.5,64.6,1
3,2009,Abril,9.4,2.5,5.8,59.8,0,6.1,5.2,5.7,86.2,1
4,2009,Mayo,6.3,-1.2,2.1,11.4,1,s/d,s/d,2.6,59.2,4
5,2009,Junio,4.5,-1.5,1.4,19.5,3,2.5,1.7,2.1,51,9
6,2009,Julio,3.3,-2.3,0.3,24.9,6,1.9,1.2,1.6,46.7,8
7,2009,Agosto,4.5,-0.9,1.6,79.5,5,2.4,1.5,1.9,43.5,1
8,2009,Septiembre,8.6,0.7,4.2,14.8,2,5.3,4.2,4.7,33,3
9,2009,Octubre,10.8,0.6,5.4,7.3,1,7.6,6.3,7,39.7,2
10,2009,Noviembre,10.5,0.9,5.6,4.9,4,5,3.8,4.4,29.8,5
11,2009,Diciembre,15.2,4.3,9.7,20.3,0,9.5,8.2,8.8,43.8,1
12,2010,Enero,13.2,5.9,10.3,85.5,0,9.7,8.4,9,84.6,0
13,2010,Febrero,12.6,6.2,9.2,40.2,0,8.5,7.5,8,66,0
14,2010,Marzo,11.9,4,8.0,21.8,0,8.3,7.2,7.7,26.8,0

In [326]:
# Corrección de error de formato detectado en el archivo fuente climático
# En temp_max_ush, noviembre y diciembre de 2022 fueron leídos como fechas.
# Según el Excel original, los valores correctos son 15.8 y 14.5.

clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2022") &
    (clima_limpio["mes"].str.upper().str.strip() == "NOVIEMBRE"),
    "temp_max_ush"
] = 15.8

clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2022") &
    (clima_limpio["mes"].str.upper().str.strip() == "DICIEMBRE"),
    "temp_max_ush"
] = 14.5

In [327]:
clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2022") &
    (clima_limpio["mes"].str.upper().str.strip().isin(["NOVIEMBRE", "DICIEMBRE"])),
    ["anio", "mes", "temp_max_ush", "temp_min_ush", "temp_media_ush", "precipitacion_ush", "nieve_ush"]
]

,anio,mes,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
166,2022,noviembre,15.8,4.9,10.3,19,-
167,2022,diciembre,14.5,5.2,9.5,58.2,-

In [328]:
# Verificamos valores faltantes
clima_limpio.isnull().sum()

anio                 0
mes                  0
temp_max_rg          0
temp_min_rg          0
temp_media_rg        0
precipitacion_rg     0
nieve_rg             0
temp_max_ush         0
temp_min_ush         0
temp_media_ush       0
precipitacion_ush    0
nieve_ush            0
dtype: int64

## Recuperación de datos faltantes mediante Open-Meteo

In [329]:
import requests

def obtener_clima_mensual_openmeteo(lat, lon, fecha_inicio, fecha_fin):
    url = "https://archive-api.open-meteo.com/v1/archive"

    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": fecha_inicio,
        "end_date": fecha_fin,
        "daily": [
            "temperature_2m_max",
            "temperature_2m_min",
            "temperature_2m_mean",
            "precipitation_sum",
            "snowfall_sum"
        ],
        "timezone": "America/Argentina/Ushuaia"
    }

    r = requests.get(url, params=params)
    r.raise_for_status()
    data = r.json()

    df = pd.DataFrame(data["daily"])
    df["fecha"] = pd.to_datetime(df["time"])
    df["anio"] = df["fecha"].dt.year.astype(str)
    df["mes_num"] = df["fecha"].dt.month

    mensual = df.groupby(["anio", "mes_num"]).agg(
        temp_max=("temperature_2m_max", "mean"),
        temp_min=("temperature_2m_min", "mean"),
        temp_media=("temperature_2m_mean", "mean"),
        precipitacion=("precipitation_sum", "sum"),
        nieve=("snowfall_sum", lambda x: (x > 0).sum())
    ).reset_index()

    meses = {
        1: "ENERO", 2: "FEBRERO", 3: "MARZO", 4: "ABRIL",
        5: "MAYO", 6: "JUNIO", 7: "JULIO", 8: "AGOSTO",
        9: "SEPTIEMBRE", 10: "OCTUBRE", 11: "NOVIEMBRE", 12: "DICIEMBRE"
    }

    mensual["mes"] = mensual["mes_num"].map(meses)

    return mensual.round(2)

In [330]:
# corregir mayo 2021 temp_min_rg
# ==========================================
# CORRECCIÓN DE TEMPERATURA MÍNIMA
# RÍO GRANDE - MAYO 2021
# Fuente: Open-Meteo
# ==========================================
rg_mayo_2021 = obtener_clima_mensual_openmeteo(
    lat=-53.7860,
    lon=-67.7000,
    fecha_inicio="2021-05-01",
    fecha_fin="2021-05-31"
)

valor_temp_min_rg = rg_mayo_2021.loc[0, "temp_min"]

clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2021") &
    (clima_limpio["mes"].str.upper().str.strip() == "MAYO"),
    "temp_min_rg"
] = valor_temp_min_rg

clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2021") &
    (clima_limpio["mes"].str.upper().str.strip() == "MAYO")
]

,anio,mes,temp_max_rg,temp_min_rg,temp_media_rg,precipitacion_rg,nieve_rg,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
148,2021,mayo,7.1,2.1,3.4,31.1,-,7.5,1.9,4.6,48.7,9

In [331]:
# recuperar Ushuaia 2024
ush_2024 = obtener_clima_mensual_openmeteo(
    lat=-54.8019,
    lon=-68.3030,
    fecha_inicio="2024-01-01",
    fecha_fin="2024-12-31"
)

for _, fila in ush_2024.iterrows():
    mask = (
        (clima_limpio["anio"].astype(str) == "2024") &
        (clima_limpio["mes"].str.upper().str.strip() == fila["mes"])
    )

    clima_limpio.loc[mask, "temp_max_ush"] = fila["temp_max"]
    clima_limpio.loc[mask, "temp_min_ush"] = fila["temp_min"]
    clima_limpio.loc[mask, "temp_media_ush"] = fila["temp_media"]
    clima_limpio.loc[mask, "precipitacion_ush"] = fila["precipitacion"]

clima_limpio.loc[
    clima_limpio["anio"].astype(str) == "2024",
    ["anio", "mes", "temp_max_ush", "temp_min_ush", "temp_media_ush", "precipitacion_ush", "nieve_ush"]
]

,anio,mes,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
180,2024,enero,12.48,5.54,9.05,115.6,...
181,2024,febrero,13.6,6.21,9.72,92.2,...
182,2024,marzo,9.67,3.34,6.51,111.6,...
183,2024,abril,6.46,0.32,3.64,139.7,...
184,2024,mayo,3.13,-1.7,0.86,126.5,...
185,2024,junio,-0.36,-6.42,-2.93,38.2,...
186,2024,julio,2.99,-3.19,0.37,97.4,...
187,2024,agosto,3.51,-1.43,1.3,51.2,...
188,2024,septiembre,3.74,-2.38,1.32,99.1,...
189,2024,octubre,8.29,1.83,5.24,77.4,...
190,2024,noviembre,10.94,3.69,7.27,100.8,...
191,2024,diciembre,11.91,5.27,8.55,113.0,...

In [332]:
# Convertimos año a texto en ambos datasets

dataset["anio"] = dataset["anio"].astype(str)
clima_limpio["anio"] = clima_limpio["anio"].astype(str)

# Verificamos tipos
dataset.info()
clima_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mes                144 non-null    object
 1   anio               144 non-null    object
 2   consumo_gas_kg     144 non-null    object
 3   cantidad_usuarios  144 non-null    object
dtypes: object(4)
memory usage: 4.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   anio               204 non-null    object
 1   mes                204 non-null    object
 2   temp_max_rg        204 non-null    object
 3   temp_min_rg        204 non-null    object
 4   temp_media_rg      204 non-null    float64
 5   precipitacion_rg   204 non-null    object
 6   nieve_rg           204 non-null    object
 7   temp_max_ush       204 non-null    object
 8   temp_min_ush       204 non-null    object
 9   temp_media_ush     204 non-null    object
 10  precipitacion_ush  204 non-null    object
 11  nieve_ush          204 non-null    object
dtypes: float64(1), object(11)
memory usage: 19.3+ KB

In [333]:
# Unimos dataset principal con dataset climático

dataset_final = pd.merge(
    dataset,
    clima_limpio,
    on=["anio", "mes"],
    how="inner"
)

# Mostramos primeras filas
dataset_final.head()

Empty DataFrame
Columns: [mes, anio, consumo_gas_kg, cantidad_usuarios, temp_max_rg, temp_min_rg, temp_media_rg, precipitacion_rg, nieve_rg, temp_max_ush, temp_min_ush, temp_media_ush, precipitacion_ush, nieve_ush]
Index: []

In [334]:
# Normalizamos nombres de meses
dataset["mes"] = dataset["mes"].str.upper().str.strip()
clima_limpio["mes"] = clima_limpio["mes"].str.upper().str.strip()

# Probamos nuevamente el merge
dataset_final = pd.merge(
    dataset,
    clima_limpio,
    on=["anio", "mes"],
    how="inner"
)

# Mostramos resultado
dataset_final.head()

,mes,anio,consumo_gas_kg,cantidad_usuarios,temp_max_rg,temp_min_rg,temp_media_rg,precipitacion_rg,nieve_rg,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
0,ENERO,2014,619090,4868.0,14.6,4.4,9.4,32,-,8.5,7.3,7.9,40.8,0
1,FEBRERO,2014,645720,4966.0,15.7,5.6,10.4,36.2,-,9.2,8,8.6,24.6,0
2,MARZO,2014,696210,4982.0,12.9,3.2,7.5,51,-,6.7,5.7,6.2,115,1
3,ABRIL,2014,717420,4888.0,10.6,1.8,5.7,29,-,6.6,5.6,6.1,24.8,1
4,MAYO,2014,1377010,5106.0,7.1,0.3,3.6,25,-,4.9,3.8,4.4,36.8,3

In [335]:
# Revisamos información general
dataset_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mes                144 non-null    object
 1   anio               144 non-null    object
 2   consumo_gas_kg     144 non-null    object
 3   cantidad_usuarios  144 non-null    object
 4   temp_max_rg        144 non-null    object
 5   temp_min_rg        144 non-null    object
 6   temp_media_rg      144 non-null    float64
 7   precipitacion_rg   144 non-null    object
 8   nieve_rg           144 non-null    object
 9   temp_max_ush       144 non-null    object
 10  temp_min_ush       144 non-null    object
 11  temp_media_ush     144 non-null    object
 12  precipitacion_ush  144 non-null    object
 13  nieve_ush          144 non-null    object
dtypes: float64(1), object(13)
memory usage: 15.9+ KB

In [336]:
# Convertimos columnas numéricas restantes

columnas_numericas = [
    "consumo_gas_kg",
    "cantidad_usuarios",
    "temp_max_rg",
    "temp_min_rg",
    "temp_media_rg",
    "precipitacion_rg",
    "nieve_rg",
    "temp_max_ush",
    "temp_min_ush",
    "temp_media_ush",
    "precipitacion_ush",
    "nieve_ush"
]

for col in columnas_numericas:
    dataset_final[col] = pd.to_numeric(
        dataset_final[col],
        errors="coerce"
    )

# Verificamos nuevamente
dataset_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mes                144 non-null    object
 1   anio               144 non-null    object
 2   consumo_gas_kg     142 non-null    float64
 3   cantidad_usuarios  142 non-null    float64
 4   temp_max_rg        144 non-null    float64
 5   temp_min_rg        144 non-null    float64
 6   temp_media_rg      144 non-null    float64
 7   precipitacion_rg   144 non-null    float64
 8   nieve_rg           43 non-null     float64
 9   temp_max_ush       144 non-null    float64
 10  temp_min_ush       144 non-null    float64
 11  temp_media_ush     144 non-null    float64
 12  precipitacion_ush  144 non-null    float64
 13  nieve_ush          83 non-null     float64
dtypes: float64(12), object(2)
memory usage: 15.9+ KB

In [337]:
# Contamos valores faltantes
dataset_final.isnull().sum()

mes                    0
anio                   0
consumo_gas_kg         2
cantidad_usuarios      2
temp_max_rg            0
temp_min_rg            0
temp_media_rg          0
precipitacion_rg       0
nieve_rg             101
temp_max_ush           0
temp_min_ush           0
temp_media_ush         0
precipitacion_ush      0
nieve_ush             61
dtype: int64

In [338]:
clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2022") &
    (clima_limpio["mes"].str.upper().str.strip().isin(["NOVIEMBRE", "DICIEMBRE"])),
    ["anio", "mes", "temp_max_ush", "temp_min_ush", "temp_media_ush", "precipitacion_ush", "nieve_ush"]
]

,anio,mes,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
166,2022,NOVIEMBRE,15.8,4.9,10.3,19,-
167,2022,DICIEMBRE,14.5,5.2,9.5,58.2,-

In [339]:
valores = clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2022") &
    (clima_limpio["mes"].str.upper().str.strip().isin(["NOVIEMBRE", "DICIEMBRE"])),
    "temp_max_ush"
]

for v in valores:
    print(repr(v))

15.8
14.5

In [340]:
clima_limpio.loc[
    (clima_limpio["anio"].astype(str) == "2022") &
    (clima_limpio["mes"].str.upper().str.strip().isin(["NOVIEMBRE", "DICIEMBRE"]))
]

,anio,mes,temp_max_rg,temp_min_rg,temp_media_rg,precipitacion_rg,nieve_rg,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
166,2022,NOVIEMBRE,16,3.6,10.1,3.1,-,15.8,4.9,10.3,19,-
167,2022,DICIEMBRE,15.9,4.5,10.3,17.5,-,14.5,5.2,9.5,58.2,-

In [341]:
# Rellenamos faltantes usando promedio histórico del mismo mes

columnas_rellenar = [
    "consumo_gas_kg",
    "cantidad_usuarios"
]

for col in columnas_rellenar:
    dataset_final[col] = dataset_final.groupby("mes")[col].transform(
        lambda x: x.fillna(x.mean())
    )

# Verificamos nuevamente
dataset_final.isnull().sum()

mes                    0
anio                   0
consumo_gas_kg         0
cantidad_usuarios      0
temp_max_rg            0
temp_min_rg            0
temp_media_rg          0
precipitacion_rg       0
nieve_rg             101
temp_max_ush           0
temp_min_ush           0
temp_media_ush         0
precipitacion_ush      0
nieve_ush             61
dtype: int64

In [342]:
# Mostrar algunos registros donde nieve_rg es NaN
dataset_final[dataset_final["nieve_rg"].isnull()][["anio","mes","nieve_rg"]].head(20)

    anio         mes  nieve_rg
0   2014       ENERO       NaN
1   2014     FEBRERO       NaN
2   2014       MARZO       NaN
3   2014       ABRIL       NaN
4   2014        MAYO       NaN
9   2014     OCTUBRE       NaN
10  2014   NOVIEMBRE       NaN
11  2014   DICIEMBRE       NaN
12  2015       ENERO       NaN
13  2015     FEBRERO       NaN
14  2015       MARZO       NaN
15  2015       ABRIL       NaN
16  2015        MAYO       NaN
20  2015  SEPTIEMBRE       NaN
21  2015     OCTUBRE       NaN
22  2015   NOVIEMBRE       NaN
23  2015   DICIEMBRE       NaN
24  2016       ENERO       NaN
25  2016     FEBRERO       NaN
26  2016       MARZO       NaN

In [343]:
# Reemplazamos valores faltantes de nieve_rg
# por 0 (sin días de nieve)

dataset_final["nieve_rg"] = dataset_final["nieve_rg"].fillna(0)

# Convertimos a entero
dataset_final["nieve_rg"] = dataset_final["nieve_rg"].astype(int)

# Verificamos nuevamente
dataset_final.isnull().sum()

mes                   0
anio                  0
consumo_gas_kg        0
cantidad_usuarios     0
temp_max_rg           0
temp_min_rg           0
temp_media_rg         0
precipitacion_rg      0
nieve_rg              0
temp_max_ush          0
temp_min_ush          0
temp_media_ush        0
precipitacion_ush     0
nieve_ush            61
dtype: int64

In [344]:
# Completar nieve_ush de 2024 usando mediana histórica mensual

for mes in dataset_final["mes"].unique():

    mediana_mes = dataset_final.loc[
        (dataset_final["anio"].astype(str) != "2024") &
        (dataset_final["mes"] == mes),
        "nieve_ush"
    ].median()

    dataset_final.loc[
        (dataset_final["anio"].astype(str) == "2024") &
        (dataset_final["mes"] == mes) &
        (dataset_final["nieve_ush"].isna()),
        "nieve_ush"
    ] = mediana_mes

In [345]:
#Convertir los NaN históricos restantes a 0

dataset_final["nieve_ush"] = dataset_final["nieve_ush"].fillna(0)
dataset_final["nieve_ush"] = dataset_final["nieve_ush"].astype(int)
dataset_final.isnull().sum()

mes                  0
anio                 0
consumo_gas_kg       0
cantidad_usuarios    0
temp_max_rg          0
temp_min_rg          0
temp_media_rg        0
precipitacion_rg     0
nieve_rg             0
temp_max_ush         0
temp_min_ush         0
temp_media_ush       0
precipitacion_ush    0
nieve_ush            0
dtype: int64

In [346]:
# Renombramos la columna anio a año

dataset_final.rename(
    columns={"anio": "año"},
    inplace=True
)

# Verificamos
dataset_final.head()

,mes,año,consumo_gas_kg,cantidad_usuarios,temp_max_rg,temp_min_rg,temp_media_rg,precipitacion_rg,nieve_rg,temp_max_ush,temp_min_ush,temp_media_ush,precipitacion_ush,nieve_ush
0,ENERO,2014,619090.0,4868.0,14.6,4.4,9.4,32.0,0,8.5,7.3,7.9,40.8,0
1,FEBRERO,2014,645720.0,4966.0,15.7,5.6,10.4,36.2,0,9.2,8.0,8.6,24.6,0
2,MARZO,2014,696210.0,4982.0,12.9,3.2,7.5,51.0,0,6.7,5.7,6.2,115.0,1
3,ABRIL,2014,717420.0,4888.0,10.6,1.8,5.7,29.0,0,6.6,5.6,6.1,24.8,1
4,MAYO,2014,1377010.0,5106.0,7.1,0.3,3.6,25.0,0,4.9,3.8,4.4,36.8,3

In [347]:
# Cantidad de filas y columnas

dataset_final.shape

(144, 14)

In [348]:
# Información general

dataset_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mes                144 non-null    object
 1   año                144 non-null    object
 2   consumo_gas_kg     144 non-null    float64
 3   cantidad_usuarios  144 non-null    float64
 4   temp_max_rg        144 non-null    float64
 5   temp_min_rg        144 non-null    float64
 6   temp_media_rg      144 non-null    float64
 7   precipitacion_rg   144 non-null    float64
 8   nieve_rg           144 non-null    int64
 9   temp_max_ush       144 non-null    float64
 10  temp_min_ush       144 non-null    float64
 11  temp_media_ush     144 non-null    float64
 12  precipitacion_ush  144 non-null    float64
 13  nieve_ush          144 non-null    int64
dtypes: float64(10), int64(2), object(2)
memory usage: 15.9+ KB

In [349]:
# ==========================================
# DIMENSIONES DE LOS DATASETS
# ==========================================

print("Dataset energético:", dataset.shape)
print("Dataset climático:", clima_limpio.shape)
print("Dataset final:", dataset_final.shape)

Dataset energético: (144, 4)
Dataset climático: (204, 12)
Dataset final: (144, 14)

In [350]:
# ==========================================
# INFORMACIÓN DEL DATASET ENERGÉTICO
# ==========================================

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mes                144 non-null    object
 1   anio               144 non-null    object
 2   consumo_gas_kg     144 non-null    object
 3   cantidad_usuarios  144 non-null    object
dtypes: object(4)
memory usage: 4.6+ KB

In [351]:
# ==========================================
# INFORMACIÓN DEL DATASET CLIMÁTICO
# ==========================================

clima_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   anio               204 non-null    object
 1   mes                204 non-null    object
 2   temp_max_rg        204 non-null    object
 3   temp_min_rg        204 non-null    object
 4   temp_media_rg      204 non-null    float64
 5   precipitacion_rg   204 non-null    object
 6   nieve_rg           204 non-null    object
 7   temp_max_ush       204 non-null    object
 8   temp_min_ush       204 non-null    object
 9   temp_media_ush     204 non-null    object
 10  precipitacion_ush  204 non-null    object
 11  nieve_ush          204 non-null    object
dtypes: float64(1), object(11)
memory usage: 19.3+ KB

In [352]:
# ==========================================
# CANTIDAD DE VALORES FALTANTES
# ==========================================

dataset_final.isnull().sum()

mes                  0
año                  0
consumo_gas_kg       0
cantidad_usuarios    0
temp_max_rg          0
temp_min_rg          0
temp_media_rg        0
precipitacion_rg     0
nieve_rg             0
temp_max_ush         0
temp_min_ush         0
temp_media_ush       0
precipitacion_ush    0
nieve_ush            0
dtype: int64

In [353]:
# Exportamos también a Excel

dataset_final.to_excel(
    "dataset_final_gas_clima_tdf.xlsx",
    index=False
)

print("Archivo Excel exportado correctamente")

Archivo Excel exportado correctamente

In [354]:
# Guardamos el dataset final limpio en CSV

dataset_final.to_csv(
    "dataset_final_gas_clima_tdf.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset exportado correctamente")

Dataset exportado correctamente